config/routes.rb
Rails.application.routes.draw do

  get 'sites/index'

  get 'sites/index/update_cities', to: 'sites#update_cities', as: 'update_cities'
  get '/sites/show/:id', to: 'sites#show', as: 'showsites'

  get '/sites/index/:id', to: 'sites#index', as: 'searchsite'
  get 'itineraries/addsite', to: 'itineraries#addsite', as: 'addsite'
  get 'itinerararies/deletesite', to: 'itineraries#deletesite', as: 'deletesite'

  get '/itineraries/show/:id', to: 'itineraries#show', as: 'itineraryshow'
  get '/itineraries/myindex' ,to: 'itineraries#myindex' ,as: 'myindex'

  devise_for :users
 

 resources :itineraries do
 	 member do
 	  put "like", to: "itineraries#upvote"
 	 end
 	end  

root 'itineraries#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/expense.rb
class Expense < ActiveRecord::Base
	serialize :parties
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
	acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>" }, default_url: "http://www.wanderlust.ly/wp-content/uploads/2015/01/destination-172x172.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  

end

app/models/itinerary_site.rb
class ItinerarySite < ActiveRecord::Base
	 has_many :itineraries
	 serialize :sitedetails
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :itineraries
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
before_action :find_itinerary, only: [:show, :edit, :update, :destroy, :upvote]
before_action :authenticate_user!, except: [:index, :show]




	def index


		@itineraries = Itinerary.all.order("created_at DESC")

	end


def myindex
    @itineraries = Itinerary.where("user_id = " + current_user.id.to_s )
end

	def show
   # @Sites = ItinerarySite.where(Itinerary = @itinerary)
       if user_signed_in?

         @loggedin = current_user.id
         @owner = Itinerary.find(@itinerary.id).user_id

       end

  
   @sites = ItinerarySite.where("itinerary_id = " + @itinerary.id.to_s)
   sitelen = @sites.length

	 @sitesarray = []
  
   for i in 0..sitelen-1

    @sitesarray << @sites[i].sitedetails
   end

  @input = @sitesarray


  @hash = Gmaps4rails.build_markers(@input) do |site, marker|
    output = site.scan(/"([^"]*)"/)
    marker.lat output[1][0]
    marker.lng output[2][0]
    marker.infowindow output[0][0]
  end 

	end


	def new


    @countries = Country.all
    @cities = City.all
		@itinerary = current_user.itineraries.build

   @itinerary = Itinerary.new

   
	end

	def create

    @countries = Country.all
    @cities = City.all

		@itinerary = current_user.itineraries.build(itinerary_params)
  
		if @itinerary.save
			#redirect_to @itinerary, notice: "Successfully created new itinerary
      redirect_to searchsite_path(@itinerary), notice: "Successfully created new itinerary"
    		else
			render 'new'
		end
	end

  def edit
 


   @sites = ItinerarySite.where("itinerary_id = " + @itinerary.id.to_s)
   sitelen = @sites.length

   @sitesarray = []
   @siteidarray = []
   for i in 0..sitelen-1
    @siteidarray << @sites[i].id
    @sitesarray << @sites[i].sitedetails
   end

  @input = @sitesarray
  	
  end
  
  def update
  	if @itinerary.update(itinerary_params)
  	  redirect_to @itinerary, notice: "Itinerary was Successfully updated"
  	else	
  		render 'edit'
  	end
  end

  def destroy
  	@itinerary.destroy
  	redirect_to root_path
  end 

  def upvote
  	@itinerary.upvote_by current_user
  	redirect_to :back
  	
  end

  def addsite

  @itinerary_id = params[:itinerary_id]

  sitedetails = []
  name = params[:name] 
  sitedetails.push(name)
  lat =  params[:latitude] 
  sitedetails.push(lat) 
  long =  params[:longitude]  
  sitedetails.push(long)
  img =  params[:image_url]
  sitedetails.push(img) 
  url =  params[:url]
  sitedetails.push(url) 
  @src = params[:src]


  @ItinerarySite = ItinerarySite.new(:itinerary_id => @itinerary_id, :sitedetails => sitedetails.to_s)

  if @ItinerarySite.save
  redirect_to itineraryshow_path(:id => @itinerary_id, :src => @src), notice: "Successfully added new site"
  else
    render 'addsite'
  end

  end


 def deletesite
  @itinerary_id = params[:itinerary_id]
  @sitename = params[:sitename]
  @itinerarysite_id = params[:itinerarysite_id]
  #ItinerarySite.where("itinerary_id = 42 and sitedetails LIKE '%Sainte-Chapelle%' ")
  #@targetdelete = ItinerarySite.where("itinerary_id = " + @itinerary_id.to_s + " and sitedetails LIKE '%" + @sitename.to_s + "%'" )
 
  ItinerarySite.destroy(@itinerarysite_id)
  redirect_to itineraryshow_path(:id => @itinerary_id ), notice: "Successfully deleted site"

  
  end 


 private

 def itinerary_params
 	params.require(:itinerary).permit(:name, :description, :image)
 end

 def find_itinerary
 	 @itinerary = Itinerary.find(params[:id])
 end

 

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
# require 'rest-client'
# require 'JSON'
# require 'yelp'
# require 'yelp4rails'
# require 'uri'



  def index
    @countries = Country.all
    @cities = City.where("country_id = ?", Country.first.id)
    @categories = Category.all
    @categorylen = Category.all.length
  end

  def show
    redirect_to :back, notice: "Please pick an interest." unless params[:activated]
    @city = City.find_by("id = ?", params[:trip][:city_id])
    @country = Country.find_by("id = ?", params[:trip][:country_id])

    @keys = {consumer_key: 'AAjxUGv8qJDJBD2HrrfHtw', consumer_secret: '-8LBfZ053iUnBE3I2wEMfi2tx-0', token: 'xOmQlVb3DCGkJUXqppqmiBLWKBOuWiPr', token_secret: '45SDkCt3uAuVzRGs_KNo25sHFn4'}
    yelp = YelpApi.new(@keys) 
    @location = URI.encode(@city.name.titleize.to_s + ' , ' + @country.name.titleize.to_s)


     if params[:activated]
    @activated_ids = params[:activated].collect {|id| id.to_i}

    @sel_category = [] 
    @topfiveresponse = []
    @remainingresponse = []

    @activated_ids.each do | sel_id| 
    @sel_category << Category.find(sel_id).name.titleize
     end

     @sel_category_arrlen = @sel_category.length

     @activated_ids.each do | sel_id|
     @selection = Category.find(sel_id).name.titleize
     @topfiveresponse << yelp.find_by(term: @selection , location: @location, sort: '0', limit: '10') 
     @remainingresponse << yelp.find_by(term: @selection , location: @location, sort: '0', limit: '5', offset: '10') 
     end
     
     @topfiveresponsearrlength  = @topfiveresponse.length
     @remainingresponsearrlength = @remainingresponse.length
    end 
  

  end

  def update_cities
    @cities = City.where("country_id = ?", params[:country_id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/cities/_city.html.erb
<option value="<%= city.id %>"><%= city.name.titleize %></option>

app/views/itineraries/_form.html.erb
<%= simple_form_for @itinerary, html: {multipart: true} do |f| %>

<% if @itinerary.errors.any? %>
  <div class="errors">
    <h2>
      <%= pluralize(@itinerary.errors.count, "error") %> prevented this itinerary from saving </h2>
  <% @itinerary.errors.full_messages.each do |msg| %>
   <li> <%= msg %> </li>
  <% end %>
  </div>
  
<% end %>

<div class="form-group"> 
  <%= f.input :image, input_html: {class: 'form-control'} %>
</div>

<div class="form-group"> 
  <%= f.input :name, input_html: { class: 'form-control'}, :required => true %>
</div>

<div class="form-group"> 
  <%= f.input :description, input_html: { class: 'form-control'} %>
</div>

  <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/itineraries/edit.html.erb
<div id=itinerary_show class="row">
  <div class="col-md-8 col-md-offset-2">
  	 <div  class="panel panel-default">

  	 	 <div  class="panel-heading">
						 <h1>Edit Itinerary</h1>
					
				</div>

				<div class="panel-body"  >	 

							<td>
               <h3>List of sites </h3>
  							
                <%  i = 0 %>
                <% @sitesarray.each do |site| %>
								 <div class="itinerary_site">
							   <%  output = site.scan(/"([^"]*)"/) %>

							   <% itinerarysiteid = @siteidarray[i] %>
                 
							   <center><p><%= image_tag (output[3][0]) %></p> </center>
							   
							   <center><h3><%= link_to output[0][0],output[4][0] %> </h3></center>

		              <center><td>
								  <%= link_to deletesite_path(:itinerary_id => params[:id] ,:sitename => output[0][0] , :itinerarysite_id => itinerarysiteid ),class: 'btn btn-default' do %>
										   <span class="glyphicon glyphicon-trash"></span>
										    Delete Site
									<% end %> 
									</td></center>
						      </div>
									     <% 	i +=1  %>
		             <% end %>
 								</td> 
 								

 								<td>
								  <center><%= link_to searchsite_path(:itinerary_id => params[:id] ),class: 'btn btn-default' do %>
										   <span class="glyphicon glyphicon-plus"></span>
										    Add a new site
									<% end %> </center>
									</td>


		</div>

							<div class="panel-footer"  >
								<td>
						    <center> <strong> Current Image </strong>
					   		<br>
					   		<%= image_tag @itinerary.image.url(:medium) %>
					   		<br> </center>

								<%= render 'form' %>
 								</td> 
							</div>


				  </div>


	 			</div>

</div>


</div>




             

app/views/itineraries/index.html.erb
<div id="itineraries" class="transitions-enabled">
	

<% @itineraries.each do | itinerary | %> 
 <div  class="box panel panel-default">

<%= link_to (image_tag itinerary.image.url), itinerary %>
   <div class="panel-body">
      <h2> <%= link_to itinerary.name, itinerary_path( :id => itinerary.id,:src => "all") %></h2>

      <p class="user"> submitted by <%= itinerary.user.email %>
            						<div class="btn btn-default btn-group pull-right">

							 	    <%= link_to like_itinerary_path(itinerary), method: :put do %> 
							 	   			<span class="glyphicon glyphicon-heart"> 
							 	   					<%= itinerary.get_upvotes.size %>
							 	   			</span> 
							 	   			<% end %>

							   </div>
							 </p>
    </div>
  </div>
<% end %>

</div>

app/views/itineraries/myindex.html.erb
<div id="itineraries" class="transitions-enabled">
	

<% @itineraries.each do | itinerary | %> 
 <div  class="box panel panel-default">

<%= link_to (image_tag itinerary.image.url), itinerary %>
   <div class="panel-body">
      <h2> <%= link_to itinerary.name, itinerary_path( :id => itinerary.id,:src => "all") %></h2>
      <p class="user"> Submitted by <%= itinerary.user.email %></p>
    </div>
  </div>
<% end %>

</div>

app/views/itineraries/new.html.erb
  <div class="col-md-6 col-md-offset-3">

  	 <div class="row">

  	 	  <div class="panel panel-default">

  	 	  	 <div class= "panel-heading">
				     <h1>New Itinerary</h1>
				   	</div>

				   	<div class="panel-body">
							<%= render 'form' %>
				    </div>

	 			</div>

			</div>

</div>

app/views/itineraries/show.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>



<div id=itinerary_show class="row">
  <div class="col-md-8 col-md-offset-2">
  	 <div  class="panel panel-default">

  	 	 <div  class="panel-heading">
						
						<h1> <%= @itinerary.name %></h1>
						<p class="description"><%= @itinerary.description %></p>	
				</div>

				<div class="panel-body" >
 						

						 <% @sitesarray.each do |site| %>
						 <div class="itinerary_site" >
					   <%  output = site.scan(/"([^"]*)"/) %>
					   <%= image_tag (output[3][0]) %>
					   <center>
					   <h3><%= link_to output[0][0],output[4][0] %> </h3>
					   </div>
            <% end %>

		 	       
				</div>

				<div class="panel-footer">
					<div class="row">
						<div class="col-md-5"> <p class="user">Created by <%= @itinerary.user.email %></p>
						</div>

						<div class="col-md-7">
							 <div class="btn-group.pull-right">

							 	   <p class= "btn btn-default" >
							 	    <%= link_to like_itinerary_path(@itinerary), method: :put do %> 
							 	   			<span class="glyphicon glyphicon-heart"> 
							 	   					<%= @itinerary.get_upvotes.size %>
							 	   			</span> 
							     </p>

							      <p class="btn btn-default"><%= link_to 'Show Map' , 'javascript:history.go(0);' %>
							 		  </p>


                      <% if user_signed_in? %>

                      <% if @loggedin == @owner %>

                      <% if params[:src] == "search" %>

                      <p class="btn btn-default"><%= link_to 'Add site', 'javascript:history.go(-1);' %>
							 		    </p>

							 		    <% end %>
							 		     
							 		      <td>
											  <%= link_to edit_itinerary_path, class: 'btn btn-default' do %>
											   <span class="glyphicon glyphicon-pencil"></span>
											  <% end %>
											  </td>




												<td>
											  <%= link_to itinerary_path, method: :delete, data: { confirm: "Are you sure ?"}, class: 'btn btn-default' do %>
											   <span class="glyphicon glyphicon-trash"></span>
											  <% end %>
											  </td>


									      <% end %>
									      <% end %>
									    <% end %>
							 </div>
						</div>			
					</div>
				</div>

                            <div style='width: 800px;'>
														<div id="map" style='width: 750px; height: 400px;'> </div>
														</div>


														<script type="text/javascript">

															handler = Gmaps.build('Google');
							

															handler.buildMap({ 

																provider: {
																
														        Zoom: 1
															}, 
															internal: {
																id: 'map'
															   }
															},
															 function(){
															markers = handler.addMarkers(<%= raw @hash.to_json %>);	
															handler.bounds.extendWith(markers);
															map.setZoom(map.getZoom());
															handler.fitMapToBounds();
														});


														

														</script>


			</div>	
	</div>			
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>PINTERAVEL </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
</head>

<body>


<nav class="navbar navbar-default">
  <div class="container">

    <div class="navbar-header navbar-brand pull-left">
   
     <p> <%= image_tag("pin.png" , height: '50', width: '50') %> 
     <%=link_to "PINTERAVEL" , root_path %> </p> 
    
    </div>  
    
    <% if user_signed_in? %>
 
    <div>
      <h3><ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Itineraries",root_path %></li>
        <li><%= link_to "My Itineraries",myindex_path %></li>
        <li><%= link_to "Create New Itinerary",new_itinerary_path %></li>
        <li><%= link_to "Account",edit_user_registration_path %></li>
        <li> <%= link_to "Sign Out",destroy_user_session_path, method: :delete %></li>
      </ul> </h3>
    </div>

    	<% else %>
    
    <div>
      <h3><ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up",new_user_registration_path %></li>
        <li><%= link_to "Sign In",new_user_session_path %></li>
      </ul> <h3>
    </div>
  

    <% end %>
    
   
  </div>
</nav>

	 <div class="container">

			<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %> 
			<% end %> 

			<%= yield %>

	</div>


</body>
</html>

app/views/sites/_form.html.erb
  <p>
  <%= form_for :trip, url: {action: "show"}, html: {method: "get"} do |f| %>
 

  <p>
  <%= image_tag("country.jpg" , height: '50', width: '50') %>
  <%=  f.label "Pick a country" %> <br> <br>
  <%= f.select :country_id, options_for_select(@countries.collect { |country| [country.name.titleize, country.id] }, 1), {}, { id: 'countries_select' } %> <br>
  </p>

  <br>
  <br>

  <p>
<%= image_tag("destination.jpg" , height: '50', width: '50') %> 
  <%= f.label "Pick a city" %> <br> <br>
  <%= f.select :city_id, options_for_select(@cities.collect { |city| [city.name.titleize, city.id] }, 0), {}, { id: 'cities_select' } %> <br>
  </p>

  <br>
  <br>
  
  <p>
   <%= image_tag("selection.png" , height: '50', width: '50') %>
   <%= f.label "Pick your interests " %> <br>
   <% @categories.each do |category| %>
   <p> <%= check_box_tag 'activated[]', category.id %>
     <%= label_tag category.name %></p>
  <% end %>
  </p>


<p>   <%= f.submit "Suprise Me !" ,class: "btn btn-primary" %> </p>

  <% end %>

app/views/sites/index.html.erb
<div class="col-md-6 col-md-offset-3">

     <div class="row">

        <div class="panel panel-default">

           <div class= "panel-heading">
             
             <h1>  What do you fancy ? </h1>
            </div>

            <div class="panel-body">
              <%= render 'form' %>
            </div>

        </div>

      </div>

</div>

app/views/sites/show.html.erb
<!-- app/views/welcome/show.html.erb -->
<% @src = "search" %>

<p><% @itinerary_id = params[:id] %></p>
 <div id=site_show class="transitions-enabled">

  	 <div  class="panel panel-default">


  	 	 <div  class="panel-heading ">
					  <h2> Top recommendations for <% for i  in 0..@sel_category_arrlen -1  %> </h2>
       			<%= @sel_category[i]  %> 
       			<% end %>
       			<%= @city.name.titleize %> , <%= @country.name.titleize %> 
				</div>

				<div class="panel-body">

	<div>	
				<% for j in 0..@topfiveresponsearrlength -1 %>
				   <% @elementsarrlength = @topfiveresponse[j]["businesses"].length %>
				    <% for i in 0..(@elementsarrlength - 1)  %>
				        <div class="site">

							 	<%= image_tag(@topfiveresponse[j]["businesses"][i]["image_url"]) %> 
				        <center>
				        <h3><%= link_to  @topfiveresponse[j]["businesses"][i]["name"], @topfiveresponse[j]["businesses"][i]["url"] %></h3> 
								
								<p><%= @topfiveresponse[j]["businesses"][i]["location"]["display_address"][0] %>,
								<%= @topfiveresponse[j]["businesses"][i]["location"]["display_address"][1] %></p>
							  <p><%= @topfiveresponse[j]["businesses"][i]["location"]["display_address"][2] %>,
								<%= @topfiveresponse[j]["businesses"][i]["location"]["display_address"][3] %> </p>
							  
						  	
								<td>
								  <%= link_to addsite_path(:itinerary_id => @itinerary_id, :name => @topfiveresponse[j]["businesses"][i]["name"],:latitude => @topfiveresponse[j]["businesses"][i]["location"]["coordinate"]["latitude"],:longitude => @topfiveresponse[j]["businesses"][i]["location"]["coordinate"]["longitude"],:image_url => @topfiveresponse[j]["businesses"][i]["image_url"],:url => @topfiveresponse[j]["businesses"][i]["url"], :src => @src), class: 'btn btn-default' do %>

								    <span class="glyphicon glyphicon-plus"></span>
								    Add Site
								  <% end %>
								</td>

						 	  </center>
			
											
							   </div>
			      <% end %>
			 <% end %> 

</div>	



				</div>




<div class="panel-footer">


				<div class="row">
						<div class="col-md-6">

							 <div class="btn-group.pull-right"> <%= link_to 'Go Back', searchsite_path %>
							 </div>
						</div>
					</div>


</div>



   

app/views/sites/showothers.html.erb
<% @src = "search" %>

<p><% @itinerary_id = params[:id] %></p>
 <div id=site_show class="transitions-enabled">

  	 <div  class="panel panel-default">


  	 	 <div  class="panel-heading ">
					  <h2> Other Recommendations <% for i  in 0..@sel_category_arrlen -1  %> </h2>
       			<%= @sel_category[i]  %> 
       			<% end %>
       			<%= @city.name.titleize %> , <%= @country.name.titleize %> 
				</div>

				<div class="panel-body">


						<% for j in 0..@remainingresponsearrlength -1 %>
						<% @remainingelementsarrlength = @remainingresponse[j]["businesses"].length %>
						<% for i in 0..(@remainingelementsarrlength - 1)  %>
						  <div class="site">

							<%= image_tag(@remainingresponse[j]["businesses"][i]["image_url"]) %> 
							<center>
							<h3><%= link_to  @remainingresponse[j]["businesses"][i]["name"], @remainingresponse[j]["businesses"][i]["url"] %></h3> 

								  <%= link_to addsite_path(:itinerary_id => @itinerary_id, :name => @remainingresponse[j]["businesses"][i]["name"],:latitude => @remainingresponse[j]["businesses"][i]["location"]["coordinate"]["latitude"],:longitude => @remainingresponse[j]["businesses"][i]["location"]["coordinate"]["longitude"],:image_url => @remainingresponse[j]["businesses"][i]["image_url"],:url => @remainingresponse[j]["businesses"][i]["url"], :src => @src), class: 'btn btn-default' do %>

								    <span class="glyphicon glyphicon-plus"></span>
								    Add Site
								  <% end %>

								 </center>

							   </div>

						<% end %>
						<% end %>


				</div>

				
				<div class="panel-footer">


								<div class="row">
										<div class="col-md-6">

											 <div class="btn-group.pull-right"> <%= link_to 'Go Back', searchsite_path %>
											 </div>
										</div>
									</div>


				</div>

			</div>
		</div>